### ISSUE TITLE
V1 Status

### ISSUE THREAD

**Issue by SebastianStehle** [SebastianStehle/mjml-net#1]
# Components

* [x] mjml
* [x] mj-head
* [x] mj-body
* [x] mj-include (NOT PLANNED)
* [x] mj-attributes (including mj-class and mj-all)
* [x] mj-breakpoint
* [x] mj-font
* [x] mj-html-attributes (NOT PLANNED)
* [x] mj-preview
* [x] mj-style
* [x] mj-style (inline) (NOT PLANNED)
* [x] mj-title
* [x] mj-accordion (NOT PLANNED)
* [x] #3
* [x] mj-carousel (NOT PLANNED)
* [x] #4
* [x] #5
* [x] #6
* [x] #7
* [x] #8
* [x] mj-navbar (V2)
* [x] mj-raw
* [x] #10
* [x] #11
* [x] #12
* [x] mj-table (V2)
* [x] #14
* [x] #71

# Rendering
* [x] beautify
* [x] minify

# Validation
* [x] #15
* [x] #16
* [x] #17
* [x] #18
* [x] #19

# Other
* [x] #20
* [x] #21

# QA
* [x] More tests for mj-column
* [x] More tests for mj-section
* [x] More tests for mj-group
* [x] Check all width container width behavior (aka getChildContext)
* [x] #62
* [x] Write high level visual tests for a few complex templates?

**Comment by SebastianStehle** [comment]
We are getting close :)

**Comment by LiamRiddell** [comment]
Crawling to the finish line 😄

**Comment by SebastianStehle** [comment]
There is at least one bug with mj-section and columns.

**Comment by SebastianStehle** [comment]
![image](https://user-images.githubusercontent.com/1236435/159058169-b209ae70-8a4c-4994-be4a-2fc79ae72b4f.png)

It could be also the image or something with the width propagation?

**Comment by SebastianStehle** [comment]
It was one bug in mj-image, but there is still a problem with contexts. We need to set the container width for the children. 

You can do this with context.Push() to create a new child context and then update the value.

**Comment by LiamRiddell** [comment]
I see, yeah, I'm still learning the context. I possibly could of messed up the calculations. The strange thing is the width of column is defined in the mj-column based on the parents child count.

It could be that we're not taking into the Box Model in the width calculations.

**Comment by SebastianStehle** [comment]
Yes, the width calculation is super strange. I also noticed the same with mj-group.

I tried to make the fix in mj-group. In mjml they have this method getChildContext(), right now we have to add a new context to the stack with context.Push() and then we can make the necessary change.

**Comment by LiamRiddell** [comment]
Yeah, I honestly think that we should change that logic to be the parent defines the child width. For mj-section it should set the width of the column and the column should just respect it. It seems like a better separation of logic. I think it would be faster too as you'd only need to calculate the width once per section regardless of column count.

**Comment by SebastianStehle** [comment]
Yes, I agree to that. Afaik it is always the same, the logic for groups and sections is more or less the same. 

I created a PR for the bugfix in mj-column. Can you review it?

**Comment by SebastianStehle** [comment]
I am going to close this now, okay?

**Comment by LiamRiddell** [comment]
@SebastianStehle Sure.

**Comment by SebastianStehle** [comment]
I think we are ready for a beta, what do you think?

**Comment by LiamRiddell** [comment]
> I think we are ready for a beta, what do you think?

I agree, I think beta is very much around the corner.

**Comment by SebastianStehle** [comment]
With beta I meant: "We are ready to push something to nuget" ;)
