### ISSUE TITLE
Rendering depends on thread culture

### ISSUE THREAD

**Issue by mcliment** [SebastianStehle/mjml-net#101]
Hi! It's me again!

If I run the tests on my machine (with "es-ES" locale), they won't work as the decimal separator in this locale is `,` instead of `.`, that is the invariant.

For example the first error for `amario.mjml` is:

```1 The values of the attributes at div(13) > table(0) > tbody(0) > tr(0) > td(0) > div(0) > table(0) > tbody(0) > tr(0) > td(0) > table(0) > tbody(0) > tr(0) > td(0)[style] are different.
 * Actual: 'vertical-align:middle;width:399,99999999999994px;'.
 * Should: 'vertical-align:middle;width:399.99999999999994px;'.
```

If I set the thread to use invariant culture the tests pass but I can imagine that it's not a good solution.

I tried to check where `"${width}px"` and similar stuff is done but putting `{width.ToInvariantString()}` everywhere is not very fool proof... may be the thread culture should be temporarily set to invariant when rendering and then restored.

I may add a PR if you want to.

**Comment by LiamRiddell** [comment]
> "${width}px"

In the case of the HeroComponent. I could be wrong here... but it's using string interpolation before passing to function `Style` function. 

So the computation would be:

EN: `$"{width}px"` -> "33.33333333px"
ES: `"${width}px" ` -> "33,33333333px"

Then then computed culture string would be passed into `.Style("width", cultureEffectedString)`. With that in mind surely the issue has already happened before entering interpolation handler?

I've searched for all occurrences of `$"{width}px"` and it appears only in the `HeroComponent` but there could be other variables for `width` which would not appear in the results. For that reason, I made a more relaxed regex `(?:\$")\{(?:[a-zA-Z]+)\}(?:[px"|%"]+)`. It's not perfect but I think it highlights all instances of this edge case.

![image](https://user-images.githubusercontent.com/3812154/160870776-2d9d93e1-d545-48db-b0f1-572d5b3b998d.png)

We could look at fixing both the String Interpolation functions and using `.ToInvariantString()`.

**Comment by SebastianStehle** [comment]
Have you seen my answer above. It should work if you just pass the CultureInfo.InvariantCulture to the interpolation handler. I am going to test that.

**Comment by LiamRiddell** [comment]
> Have you seen my answer above. It should work if you just pass the CultureInfo.InvariantCulture to the interpolation handler. I am going to test that.

Apologies, I didn't see the comment above. Ignore my rambling :D

**Comment by mcliment** [comment]
Awesome @SebastianStehle!

**Comment by mcliment** [comment]
@SebastianStehle I see that it still happens in some cases, although most of them were fixed.

For example, for tempalte `arturia.mjml`, using es-ES culture shows some errors. This is the first: 

```
1 The text in style(7) > #text(0) is different.
 * Actual: '
    @media only screen and (min-width:480px) {
      .mj-column-per-33-333333333333336 {
width:33,333333333333336% !important;
max-width: 33,333333333333336%;
}
      .mj-column-per-100 {
width:100% !important;
max-width: 100%;
}
      .mj-column-per-25 {
width:25% !important;
max-width: 25%;
}
    }
  '.
 * Should: '
    @media only screen and (min-width:480px) {
      .mj-column-per-33-333333333333336 {
        width: 33.333333333333336% !important;
        max-width: 33.333333333333336%;
      }

      .mj-column-per-100 {
        width: 100% !important;
        max-width: 100%;
      }

      .mj-column-per-25 {
        width: 25% !important;
        max-width: 25%;
      }
    }

  '.
``` 
It seems that not all paths go though the interpolator. 

I can take a look tomorrow if you need some help.

**Comment by LiamRiddell** [comment]
I believe this is the offending line https://github.com/SebastianStehle/mjml-net/blob/main/Mjml.Net/Components/Body/ColumnComponent.cs#L284.

Here's the function:
```csharp
private string GetColumnClass (GlobalContext context) {
    string className;

    // Correctly uses ToInvariantString();
    if (CurrentWidth.Unit == Unit.Percent) {
        className = $"mj-column-per-{CurrentWidth.Value.ToInvariantString().Replace('.', '-')}";
    } else {
        className = $"mj-column-px-{CurrentWidth.Value.ToInvariantString().Replace('.', '-')}";
    }

    // CurrentWidth.WidthString lacks the ToInvariantString() usage.
    context.SetGlobalData (className, MediaQuery.Width (className, CurrentWidth.WidthString));

    return className;
}
```

**Comment by mcliment** [comment]
Just ran the tests locally and works like a charm, nice! Thanks a lot @LiamRiddell @SebastianStehle 🎉 💯

**Comment by SebastianStehle** [comment]
Thanks for your feedback :)

**Comment by SebastianStehle** [comment]
What have you used before?

**Comment by mcliment** [comment]
> What have you used before?

More or less what you use in the ComplexTests, launch an external node process to do the job and in case of failure, call the API, but nothing can compare to a native .NET library.
