### ISSUE TITLE
Don't Exclude UGG Royale from Complex Tests

### ISSUE THREAD

**Issue by LiamRiddell** [SebastianStehle/mjml-net#105]
## Issue
After reviewing another ticket. I can see we're ignoring the UGG Royale template from the ComplexTests with the comment "Carousel" which leads me to believe this was implemented before the Carousel which was our last component. 

## Code Location
https://github.com/SebastianStehle/mjml-net/blob/main/Tests/ComplexTests.cs#L10-L13

## Solution
Remove the UGG Royale from the excluded templates `HashSet<string>` but keep the exclusion functionality for future.

**Comment by LiamRiddell** [comment]
Actually, the CSS is painful to compare. Ignore this.

**Comment by SebastianStehle** [comment]
Which CSS?

**Comment by SebastianStehle** [comment]
Ah, I remember. It was the problem with the IDs.
