### ISSUE TITLE
ColumnComponent.HasGutter() ignores padding

### ISSUE THREAD

**Issue by skybber** [SebastianStehle/mjml-net#112]
Code

https://github.com/SebastianStehle/mjml-net/blob/main/Mjml.Net/Components/Body/ColumnComponent.cs#L292

does not contain check for padding as is in referential impl:

https://github.com/mjmlio/mjml/blob/master/packages/mjml-column/src/index.js#L207

**Comment by SebastianStehle** [comment]
It is not necessary, because in the code generation, the padding is split into the four single properties.

**Comment by SebastianStehle** [comment]
https://github.com/SebastianStehle/mjml-net/blob/main/Mjml.Net.Generator/BindGenerator.cs#L190

**Comment by skybber** [comment]
Thanks for explanation!

**Comment by skybber** [comment]
May be there is `border` mistaken for `margin`

https://github.com/SebastianStehle/mjml-net/blob/main/Mjml.Net.Generator/BindGenerator.cs#L210
