### ISSUE TITLE
letter-spacing:none in tests of Text component

### ISSUE THREAD

**Issue by skybber** [SebastianStehle/mjml-net#117]
All tests' samples of Text component contains redundant `letter-spacing:none`, most likely it doesn't matter (since it is default and html comparer ignores it), but referential JS implementation does not generate it.

**Comment by SebastianStehle** [comment]
Perhaps the samples have been created from the online editor of the mjml website, which is not always up to date with the latest mjml version. Something like that I remember.

**Comment by skybber** [comment]
It seems that it is fixed in the online editor now.
