### ISSUE TITLE
Typo in nmax-width / nwidth

### ISSUE THREAD

**Issue by skybber** [SebastianStehle/mjml-net#120]
I'm not sure if it is typo or intention, but when I compare generated style to referention implementation it contains `nmax-width`, `nwidth` instead of `max-width`, `width` :

possible problem is at:

https://github.com/SebastianStehle/mjml-net/blob/main/Mjml.Net/Helpers/Style.cs#L17

**Comment by SebastianStehle** [comment]
There is a new line before that. `\r\n`

**Comment by skybber** [comment]
Ah, I see it now... I'm sorry for that!
