### ISSUE TITLE
Button width evaluation is incorrect

### ISSUE THREAD

**Issue by skybber** [SebastianStehle/mjml-net#123]
According mjml, width calculation is using `getShorthandAttrValue` parser, that destruct composed `inner-padding` attribute:

https://github.com/mjmlio/mjml/blob/master/packages/mjml-button/src/index.js#L117

.Net impl uses `padding-left` and `padding-right`:

https://github.com/SebastianStehle/mjml-net/blob/main/Mjml.Net/Components/Body/ButtonComponent.cs#L191

I suggest to add attributes `inner-padding-left,right,top,bottom` and use attribute expansion mechanism instead of parsing inner-padding in rendering.

**Comment by skybber** [comment]
Pby `inner-padding` should be add to candidates for expansion:

https://github.com/SebastianStehle/mjml-net/blob/main/Mjml.Net.Generator/BindGenerator.cs#L210

**Comment by SebastianStehle** [comment]
It does that, because it uses Contains and EndsWith checks, I have tested that.
