### ISSUE TITLE
Question about priority of inherited attribute

### ISSUE THREAD

**Issue by skybber** [SebastianStehle/mjml-net#125]
It's not clear to me what's the priority of inherited attribute in .net impl. Is it (from high to low):

1. attribute at element
2. inherited
3. mj-class
5. mj-[component_name]
6. mj-all

?

**Comment by skybber** [comment]
I had to change it to 1 3, 2, 4, 5 to be compatible with JS implementation.

**Comment by SebastianStehle** [comment]
Do you have a test for that?

**Comment by SebastianStehle** [comment]
I guess you are right. Here they are merged: https://github.com/mjmlio/mjml/blob/9558a4b0b416b6458c586d48f0c77219760ed6d7/packages/mjml-core/src/createComponent.js#L228

**Comment by SebastianStehle** [comment]
But should the order not be 3, 4, 5, 1, 2?

**Comment by skybber** [comment]
I don't have a test, my conclusion was based on comparison of outcomes from JS versus java implementation.
