### ISSUE TITLE
Border expansion pby incorrect

### ISSUE THREAD

**Issue by skybber** [SebastianStehle/mjml-net#128]
CSS border attribute has different syntax then padding, size/geometry is only in first component, but BindingHelper expects geometry in all components.

**Comment by SebastianStehle** [comment]
What?

**Comment by skybber** [comment]
I expect, that `border` attr is expanded in same way like `padding` :

https://github.com/SebastianStehle/mjml-net/blob/main/Mjml.Net.Generator/BindGenerator.cs#L210

but CSS `border` has syntax: `border: border-width border-style border-color|initial|inherit;`

**Comment by SebastianStehle** [comment]
So in case of borders we just do not have to make the split, right?

**Comment by skybber** [comment]
I suggest to use first component and expand it to left/right/top/bottom

**Comment by skybber** [comment]
But `CalculateButtonWidth` need only `left` and `right`, so `top`, `bottom` is not necessary

**Comment by SebastianStehle** [comment]
yes, but it does not really matter anyway. It is a "noop"

**Comment by skybber** [comment]
It seems that border could contain more complex value. Dimension of border is not necessary first value, standard mjml parser uses `borderParser` function, that look for first integer value without units - seems wrong to me. Correctly it should be <float_number><units>

example:
```
<mjml>
  <mj-body>
    <mj-section>
      <mj-column border="solid 1px black">

        <mj-image width="100px" src="/assets/img/logo-small.png"></mj-image>

        <mj-divider border-color="#F45E43"></mj-divider>

        <mj-text font-size="20px" color="#F45E43" font-family="helvetica">Hello World</mj-text>

      </mj-column>
    </mj-section>
  </mj-body>
</mjml>
```
