### ISSUE TITLE
MjColumn - padding-top/bottom used for width evaluation

### ISSUE THREAD

**Issue by skybber** [SebastianStehle/mjml-net#130]
I've found deviation from JS implementation in the way how the `innerWidth` of `mj-column` is evaluated. In .Net impl `padding-top` and `pading-bottom` is used for `width`:

https://github.com/SebastianStehle/mjml-net/blob/main/Mjml.Net/Components/Body/ColumnComponent.cs#L121

it seems not to be correct, since in case of large top/bottom padding the child component (e.g. mj-image) is very small.

**Comment by SebastianStehle** [comment]
Should be paddingLeft and PaddingRight I guess.

**Comment by skybber** [comment]
You are right.
