### ISSUE TITLE
Social inner-padding is inherited in SocialElement as padding

### ISSUE THREAD

**Issue by skybber** [SebastianStehle/mjml-net#131]
According 

https://github.com/mjmlio/mjml/blob/master/packages/mjml-social/src/Social.js#L58

`SocialElement` gets padding value from parent `Social` componen's inner-padding, pby it uses it if is default or null ?

**Comment by SebastianStehle** [comment]
What is `pby`. But yes, I think it transforms `inner-padding => padding`

**Comment by SebastianStehle** [comment]
Fixed.
