### ISSUE TITLE
Attribute value from last mj-class is used 

### ISSUE THREAD

**Issue by skybber** [SebastianStehle/mjml-net#132]
There can specified be more `mj-class` per component, if any two of them specify the same attribute then the the last one is used, but .Net impl uses the first one:

https://github.com/SebastianStehle/mjml-net/blob/main/Mjml.Net/Internal/Binder.cs#L66

see:
```
<mjml>
  <mj-head>
    <mj-attributes>
      <mj-class name="blue" color="blue" />
      <mj-class name="red" color="red" />
    </mj-attributes>
  </mj-head>  
  <mj-body>
        <mj-text mj-class="blue red">Hello World</mj-text>
  </mj-body>
</mjml>
```

**Comment by SebastianStehle** [comment]
Do you have a test case for that?
