### ISSUE TITLE
widthParser is missing 

### ISSUE THREAD

**Issue by skybber** [SebastianStehle/mjml-net#133]
There is width parser in the JS  implementation:

https://github.com/mjmlio/mjml/blob/master/packages/mjml-core/src/helpers/widthParser.js

in .Net implementation the width parser is missing and common `UnitParser` is used instead of it. It is quite OK if unit is presents, but if it is missing then according JS implementation the 'px' should be used.

**Comment by SebastianStehle** [comment]
Not sure what you want to tell me with that. If there is a concrete bug, I need something to reproduce or a use case. Why should I not generalize logic, if it makes sense?

**Comment by skybber** [comment]
May be it is OK, but JS implementation render following button with `width="450px"`, even without explicit Units (px is default for width):
'''
<mjml>
  <mj-body>
    <mj-section>
      <mj-column>
        <mj-button width="500">Click</mj-button>
      </mj-column>
    </mj-section>
  </mj-body>
</mjml>
'''

**Comment by SebastianStehle** [comment]
I see.

**Comment by SebastianStehle** [comment]
Perhaps a default unit can be added and then just round everything except percentage

**Comment by skybber** [comment]
Yes, px is default for width:

https://github.com/mjmlio/mjml/blob/master/packages/mjml-core/src/helpers/widthParser.js#L16

**Comment by SebastianStehle** [comment]
MJML is buggy here as well. Because the width attribute should not have a unit:

https://www.dofactory.com/html/img/width#:~:text=The%20width%20attribute%20specifies%20the,use%20the%20CSS%20width%20property.
