### ISSUE TITLE
Update mjml.io documentation to reflect support for <mj-include>

### ISSUE THREAD

**Issue by LiamRiddell** [SebastianStehle/mjml-net#143]
We need to get the official mjml documentation changed to remove the bullet point referring to `mj-include` support.

@SebastianStehle, did you reach out to the MJML team for this to be added to official documentation?

Source: https://documentation.mjml.io/#net-mjml-net

**Comment by SebastianStehle** [comment]
Yes, I just created a PR to the docs.

**Comment by LiamRiddell** [comment]
> Yes, I just created a PR to the docs.

Okay, I'll put this on my todo list and I'll get that fixed.

**Comment by LiamRiddell** [comment]
@SebastianStehle, I've reated PR on the official documents. It should hopefully be updated soon.

**Comment by LiamRiddell** [comment]
Closing, official documentation has been updated.
