### ISSUE TITLE
BorderRadius should be BindType.FourPixelsOrPercent

### ISSUE THREAD

**Issue by skybber** [SebastianStehle/mjml-net#145]
There are several components with BorderRadius attribute. I've checked js implementation with `mj-button` and it seems that it allows any value (String). It seems incorrect to me, but the type should be unified in the .Net impl to `BindType.FourPixelsOrPercent`

**Comment by SebastianStehle** [comment]
The components that we added later have partially been generated from mjml directly.

**Comment by SebastianStehle** [comment]
Closed by last commit
