### ISSUE TITLE
MjImage is malformed

### ISSUE THREAD

**Issue by farhadnowzari** [SebastianStehle/mjml-net#160]
Hi,

thanks for the great library, I was just reading the code and realized you have implemented mjml without nodejs cool ^^;

The issue I experiences which is minor but want to make sure that it won't be problematic was rendering the following sample:
https://mjml.io/try-it-live/De-2ZNLsr

The sample above is from mjml and after rendering using `mjml-net` the image at the top is full width instead if `150px`. But if I put it into a `<mj-tabl>` and use normal `<img>` then it will work, but wanna make sure that this will be consistent through other mail engines

**Comment by SebastianStehle** [comment]
Hi,

thanks a lot for the bug report. Unfortunately I cannot reproduce it.

**Comment by farhadnowzari** [comment]
> Hi,
> 
> thanks a lot for the bug report. Unfortunately I cannot reproduce it.

Hi, thanks for your reply.

this is the result I get.

![image](https://user-images.githubusercontent.com/57224511/219610433-07f08243-d4b0-400e-8aa3-d8df25c64928.png)

I tested the generated `html` in https://app.postdrop.io/

**Comment by farhadnowzari** [comment]
> > Hi,
> > thanks a lot for the bug report. Unfortunately I cannot reproduce it.
> 
> Hi, thanks for your reply.
> 
> this is the result I get.
> 
> ![image](https://user-images.githubusercontent.com/57224511/219610433-07f08243-d4b0-400e-8aa3-d8df25c64928.png)
> 
> I tested the generated `html` in https://app.postdrop.io/

well, nevermind I think it is an issue with that test website, because the actual mjml generated html get's malformed

**Comment by SebastianStehle** [comment]
O added the sample template to our tests and it shows no errors. I also opened the generated file using edge and it looked identical to me.

**Comment by farhadnowzari** [comment]
> O added the sample template to our tests and it shows no errors. I also opened the generated file using edge and it looked identical to me.

I think the issue was with that website.
I tested the library last night with our notification service and it worked very fine on different mail engines.
I will close this.

**Comment by SebastianStehle** [comment]
Thanks for the update
