### ISSUE TITLE
Question: Is it possible to override the default styles?

### ISSUE THREAD

**Issue by Robw94** [SebastianStehle/mjml-net#165]
Hi, new to working with Mjml and am currently using this package to render from mjml to html. However I have a slight problem.

My users want to be able to use the 'Roboto' (fine this is default) and the 'Roboto+Slab' fonts.

I tried overriding the 'Fonts' on the MjmlOptions and this has made the other default fonts drop out of the stylesheet ref in the HTML (this is fine) but only Roboto is showing, not Roboto+Slab
`            IReadOnlyDictionary<string, Mjml.Net.Helpers.Font> fonts = new Dictionary<string, Mjml.Net.Helpers.Font>
            {
                {"Roboto Slab", slab },
                {"Roboto", roboto }
            };`

    
  
  
 When I manually edit the html in an editor and create a new import + href to roboto+slab it works fine.
```
 <link href="https://fonts.googleapis.com/css?family=Roboto+Slab&display=swap" rel="stylesheet" type="text/css" />
 @import url(https://fonts.googleapis.com/css?family=Roboto+Slab&display=swap );
```
Is there a way to get this to work using MjmlOptions? or would I have to find+replace this in code myself after the HTML has been generated?

**Comment by SebastianStehle** [comment]
You can import any font as described here: 

https://documentation.mjml.io/#mj-font

But mjml and mjml-net also support a list of default fonts. If one of these fonts is detected (e.g. the font-family attribute is used somehwere) the font is added automatically. You can also add custom fonts if you want.
