### ISSUE TITLE
<td> attribute is valign not vertical-align 

### ISSUE THREAD

**Issue by skybber** [SebastianStehle/mjml-net#169]
At the following line atribute `vertical-align=` instead of `valign=` is appended to <td> attributes:
https://github.com/SebastianStehle/mjml-net/blob/f834b2b4e4f99fd61ce5f32a34e0e86676680962/Mjml.Net/Components/Body/ColumnComponent.cs#L215

**Comment by SebastianStehle** [comment]
Where do you see it here?

https://github.com/mjmlio/mjml/blob/master/packages/mjml-column/src/index.js#L298

**Comment by skybber** [comment]
I think that's wrong even in JS implementation:

https://github.com/mjmlio/mjml/blob/master/packages/mjml-column/src/index.js#L261

**Comment by SebastianStehle** [comment]
Probably. But then tests might fail...

**Comment by SebastianStehle** [comment]
Will be fixed as soon as the mjml bug is fixed: https://github.com/mjmlio/mjml/issues/2684

**Comment by SebastianStehle** [comment]
Should already be fixed.
