### ISSUE TITLE
Support for mj-list

### ISSUE THREAD

**Issue by drgrieve** [SebastianStehle/mjml-net#170]
https://github.com/premail/mjml-bullet-list

I've just started using this package and it's been great, and I'll be looking to using this package for new projects going forward, and drop my internal email builder.

However just noticed that a template given to me to implement using mj-list (which is not a standard component)

Do you think this would be easy enough to implement?

**Comment by SebastianStehle** [comment]
Theoretically yes, but we do not have this renderedMJML function yet. But it could be similar to mj-include. If you want to provide a PR I can support you.
