### ISSUE TITLE
Asynchronous rendering

### ISSUE THREAD

**Issue by ClassTerr** [SebastianStehle/mjml-net#173]
It seems this library doesn't support asynchronous operations. In particular, IFileLoader works completely synchronously, which is not the best way to work with files in .NET since it blocks the thread until the file is loaded. It's getting even worse in my case, since I need to fetch them via network. I want to know if async overloads are planned for future development or if they are not implemented due to performance implications. Thanks!

**Comment by SebastianStehle** [comment]
Hi, it is not planned, because of performance. If you need async loading we could make some preloading operation that provides all includes or something like that. PRs are welcome.

Then it would look like this

```
var loader = new NetworkLoader();
var includes = mjmlRenderer.GetAllIncludes(mjml);
await loader.LoadAllAsync(includes);
return mjmlRenderer.Render(mjml);
```

**Comment by SebastianStehle** [comment]
The parsing is super fast. Most benchmarks are below 1ms on our developer machines and the parsing takes only 40-50% of that time. So the extra parsing would be only fraction of that, perhaps a 20% overhead = 200ns. I am pretty sure that asynchronous code would make it slower than the double parsing.

**Comment by SebastianStehle** [comment]
I just tested it:

```
using System.Diagnostics;

namespace ConsoleApp;

internal partial class Program
{
    static void Main(string[] args)
    {
        var file = File.ReadAllText("amario.mjml");

        static IEnumerable<string> Parse(string file)
        {
            HashSet<string>? includes = null;

            var span = file.AsSpan();

            var trimChars = new char[] { '\'', '"', ' ' };

            while (true)
            {
                var indexOfPath = span.IndexOf("path=");
                if (indexOfPath < 0)
                {
                    break;
                }

                span = span[(indexOfPath + 6)..];

                var indexOfEnd = span.IndexOfAny('\'', '"');
                if (indexOfEnd <= 0)
                {
                    break;
                }

                includes ??= new HashSet<string>();
                includes.Add(span[..indexOfEnd].Trim(trimChars).ToString());

                span = span[indexOfEnd..];
            }

            return includes as IEnumerable<string> ?? Array.Empty<string>();
        }

        Parse(file);

        var found = 0;

        var watch = Stopwatch.StartNew();
        for (var i = 0; i < 100; i++)
        {
            found = Parse(file).Count();
        }
        watch.Stop();

        Console.WriteLine($"Elapsed: {watch.Elapsed / 100}, found: {found}");
    }
}
```

I used the amario template and added 4 includes to the file. One at the very end.

The result:

```
Elapsed: 00:00:00.0000041, found: 3
```

Thats 4ns. I would not be concerned about performance ;)

**Comment by SebastianStehle** [comment]
I think this has been solved.
