### ISSUE TITLE
IFileLoader can't handle nested files

### ISSUE THREAD

**Issue by ClassTerr** [SebastianStehle/mjml-net#179]
In current implementation, includes for `mj-include` rather more treated as a key-value collection than paths. This makes it impossible to locate nested files for `mj-include`. 
Let me show an example to make things clearer of what I mean. Let's say we have next file structure:

`Test.mjml`
```xml
<mjml>
    <mj-body>
        <mj-include path="Partials/Header.mjml"></mj-include>
        <mj-section>
            <mj-column>
                <mj-text>Hello! It's Test.mjml</mj-text>
            </mj-column>
        </mj-section>
    </mj-body>
</mjml>

```

`Partials/Header.mjml`
```xml
<mjml>
    <mj-body>
        <mj-include path="HeaderComponents/HeaderLogo.mjml"></mj-include>
        <mj-section>
            <mj-column>
                <mj-text>Hello! This is a Header.mjml</mj-text>
                <mj-divider></mj-divider>
            </mj-column>
        </mj-section>
    </mj-body>
</mjml>

```
`Partials/HeaderComponents/HeaderLogo.mjml`
```xml
<mjml>
    <mj-body>
        <mj-section>
            <mj-column>
                <mj-text>Hello, I am HeaderLogo.mjml</mj-text>
                <mj-divider></mj-divider>
            </mj-column>
        </mj-section>
    </mj-body>
</mjml>
```

So, I expect all three files to be rendered. Note that in `Partials/Header.mjml` file we have `mj-include` that is pointing to `HeaderComponents/HeaderLogo.mjml`. This path is relative to `Partials/Header.mjml`, and not to the root rendering file (`Test.mjml`)

This is what I get after running native mjml:
`mjml Test.mjml -o test.html`
![image](https://github.com/SebastianStehle/mjml-net/assets/30635839/160354f7-1187-4e5e-b8bf-24dd3fdaa597)

But when it comes to mjml.net, things are not the same. In order to work with files, I have created a file provider:
```csharp
public class EmailTemplateFileLoader : IFileLoader
{
    private readonly string _templateFolder;

    public EmailTemplateFileLoader(string templateFolder)
    {
        _templateFolder = templateFolder;
    }

    public static EmailTemplateFileLoader CreateForFile(string fileAbsolutePath)
    {
        return new EmailTemplateFileLoader(Path.GetDirectoryName(fileAbsolutePath) ?? "");
    }

    public bool ContainsFile(string templateRelativePath)
    {
        return File.Exists(GetAbsolutePath(templateRelativePath));
    }

    public string LoadText(string templateRelativePath)
    {
        return File.ReadAllText(GetAbsolutePath(templateRelativePath));
    }

    private string GetAbsolutePath(string templateRelativePath)
    {
        return Path.Combine(_templateFolder, templateRelativePath);
    }
}
```

Then I use mjml.net like this:
```csharp
var templateToRenderAbsolutePath = "C:\\Templates\\Test.mjml"
var template = File.ReadAllText(templateToRenderAbsolutePath);

var mjmlRenderer = new MjmlRenderer();
var options = new MjmlOptions
{
    FileLoader = EmailTemplateFileLoader.CreateForFile(templateToRenderAbsolutePath)
};

var (html, errors) = mjmlRenderer.Render(template, options);
```

And getting the next error:
```
System.IO.DirectoryNotFoundException: Could not find a part of the path 'C:\Templates\HeaderComponents\HeaderLogo.mjml'
```
But the correct path should be `C:\Templates\Partials\HeaderComponents\HeaderLogo.mjml`

It seems I can't do anything about it since I need a path of currently processing mjml file (not just root file like now) inside my implementation of IFileLoader, but it is not provided by mjml.net library.

Please note that searching by file name is not the case for me since there can be files with the same name but in different folders.

I believe contracts breaking in `IFileLoader` is required to fix this issue, so I am not expecting it to be done soon. Maybe I am just missing something and it is possible to operate correctly right now?

Any help appreciated.

**Comment by SebastianStehle** [comment]
Hi,

this can be changed soon. I don't see any problems with that.

**Comment by SebastianStehle** [comment]
It has been implemented. See: https://github.com/SebastianStehle/mjml-net/blob/main/Mjml.Net/InMemoryFileLoader.cs
