### ISSUE TITLE
Upgrading to v2 or latest version removes .fixXML() and Lax

### ISSUE THREAD

**Issue by Robw94** [SebastianStehle/mjml-net#183]
Tried to upgrade from 1.1.18 to 2 and latest and .FixXML() and the 'lax' option has been removed. (lax is fine, but wanted to fix any possible broken xml)

Now even with very basic mjml templates they are not returning once rendered even tho they are being parsed in. (I can see the generated mjml, when i call .render it returns a blank html template)

Using net7

**Comment by SebastianStehle** [comment]
Hi,

the fixXML should be not necessary anymore, because we switched to a html parser that works as described in the html spec. I have no idea why your template does not return anything, in our tests we run all major templates from the gallery.

**Comment by Robw94** [comment]
`            var mjml = @"<mjml>
  <mj-head>

    <mj-html-attributes>
      <mj-html-attribute class=""easy-email"" multiple-attributes=""false"" attribute-name=""content-background-color"" content-background-color=""#ffffff""></mj-html-attribute>
      <mj-html-attribute class=""easy-email"" multiple-attributes=""false"" attribute-name=""text-color"" text-color=""#000000""></mj-html-attribute>
      <mj-html-attribute class=""easy-email"" multiple-attributes=""false"" attribute-name=""font-family"" font-family=""-apple-system, BlinkMacSystemFont, &#x27;Segoe UI&#x27;, &#x27;Roboto&#x27;, &#x27;Oxygen&#x27;, &#x27;Ubuntu&#x27;, &#x27;Cantarell&#x27;, &#x27;Fira Sans&#x27;, &#x27;Droid Sans&#x27;,&#x27;Helvetica Neue&#x27;, sans-serif""></mj-html-attribute>
      <mj-html-attribute class=""easy-email"" multiple-attributes=""false"" attribute-name=""font-size"" font-size=""12px""></mj-html-attribute>
      <mj-html-attribute class=""easy-email"" multiple-attributes=""false"" attribute-name=""line-height"" line-height=""1.7""></mj-html-attribute>
      <mj-html-attribute class=""easy-email"" multiple-attributes=""false"" attribute-name=""font-weight"" font-weight=""400""></mj-html-attribute>
      <mj-html-attribute class=""easy-email"" multiple-attributes=""false"" attribute-name=""responsive"" responsive=""true""></mj-html-attribute>

    </mj-html-attributes>




    <mj-breakpoint width=""480px"" />


    <mj-attributes>
      <mj-text font-size=""14px"" />
      <mj-text line-height=""1.7"" />
      <mj-text font-weight=""400"" />
      <mj-text font-size=""12px"" />
      <mj-all font-family=""-apple-system, BlinkMacSystemFont, &#x27;Segoe UI&#x27;, &#x27;Roboto&#x27;, &#x27;Oxygen&#x27;, &#x27;Ubuntu&#x27;, &#x27;Cantarell&#x27;, &#x27;Fira Sans&#x27;, &#x27;Droid Sans&#x27;,&#x27;Helvetica Neue&#x27;, sans-serif"" />
      <mj-text font-size=""12px"" />
      <mj-text color=""#000000"" />
      <mj-text line-height=""1.7"" />
      <mj-text font-weight=""400"" />
      <mj-wrapper background-color=""#ffffff"" />
      <mj-section background-color=""#ffffff"" />


    </mj-attributes>
  </mj-head>
  <mj-body background-color=""#efecec"" width=""600px"">
    <mj-wrapper padding=""0px 0px 0px 0px"" border=""none"" direction=""ltr"" text-align=""center"">
      <mj-section background-repeat=""repeat"" background-size=""auto"" background-position=""top center"" border=""none"" direction=""ltr"" text-align=""center"" background-color=""#0C243E"" padding=""0px 0px 0px 0px"">
        <mj-column border=""none"" vertical-align=""top"" width=""50%"" padding=""0px 0px 0px 0px"">
          <mj-text align=""left"" container-background-color=""#0C243E"" color=""#FFFFFF"" padding=""10px 25px 10px 25px"">
            <font face=""Arial"" size=""5"">Written Statements</font>
          </mj-text>
        </mj-column>
        <mj-column border=""none"" vertical-align=""top"" width=""50%"" padding=""0px 0px 0px 0px""></mj-column>
      </mj-section>
      <mj-section background-repeat=""repeat"" background-size=""auto"" background-position=""top center"" border=""none"" direction=""ltr"" text-align=""left"" padding=""0px 0px 0px 0px"">
        <mj-column border=""none"" vertical-align=""top"" padding=""0px 0px 0px 0px"">
          <mj-text align=""left"" font-family=""Arial"" container-background-color=""#0C243E"" color=""#FFFFFF"" font-size=""14px"" padding=""6px 25px 10px 25px"">
            <div style=""text-align: left;"">&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;&nbsp;Friday, 06 October 2023</div>
          </mj-text>
        </mj-column>
      </mj-section>
      <mj-section background-repeat=""repeat"" background-size=""auto"" background-position=""top center"" border=""none"" direction=""ltr"" text-align=""left"" padding=""0px 0px 0px 0px"">
        <mj-column border=""none"" vertical-align=""top"" padding=""0px 0px 0px 0px"">
          <mj-text align=""left"" font-size=""14px"" font-family=""Arial"" padding=""10px 25px 10px 25px"">
            <div><b>Name of SoS and Department<br></b>1. Name of Statement<br><br><b>Name of SoS and Department<br></b>2. Name of Statement<br></div>
            <div><br></div>
          </mj-text>
        </mj-column>
      </mj-section>
      <mj-section background-repeat=""repeat"" background-size=""auto"" background-position=""top center"" border=""none"" direction=""ltr"" text-align=""left"" padding=""0px 0px 0px 0px"">
        <mj-column border=""none"" vertical-align=""top"" padding=""0px 0px 0px 0px"">
          <mj-text align=""left"" font-weight=""bold"" font-family=""Roboto"" font-size=""14px"" padding=""10px 25px 10px 25px"">
            <font size=""2"" style=""font-weight: normal;"" face=""Arial"">Log on to for all the latest information on upcoming events</font><br>
          </mj-text>
        </mj-column>
      </mj-section>
    </mj-wrapper>
  </mj-body>
</mjml>";
 var (html, errors) = mjmlRenderer.Render(mjml, options);`


![image](https://github.com/SebastianStehle/mjml-net/assets/46281347/12197ad1-5c65-40cc-b423-397ef4cdb3f0)

Mjml is valid and viewable in the online editor on official website, however I get a blank html output

**Comment by SebastianStehle** [comment]
But this looks like a bug for me.

**Comment by Robw94** [comment]
Ive just added a Regex that strips out that element for now

**Comment by SebastianStehle** [comment]
I have already fixed that in 3.2.0
