### ISSUE TITLE
E-mail formatting broke after upgrade from 1.2.0 to 3.1.0

### ISSUE THREAD

**Issue by FixFlare** [SebastianStehle/mjml-net#184]
I've been using MJML .net for quite some time in one of my projects - thanks

I had been using version 1.2 for months but recently upgraded to 3.1.0 and one of my e-mail templates is now completely out of whack.

I just tried to upgrade to 3.2.0 - same issue.

I've tried to get my template down to the bare minimum to demonstrate the problem.

The following MJML works correctly on [https://mjml.io/try-it-live]( https://mjml.io/try-it-live) but is rendered incorrectly in MJML .net

```mjml
<mjml>
  <mj-head>
    <mj-title>test</mj-title>
    <mj-preview>test</mj-preview>
    <mj-attributes>
      <mj-all font-family="Calibri, Arial"></mj-all>
      <mj-table></mj-table>
      <mj-text font-weight="400" font-size="16px" color="#000000" line-height="24px"></mj-text>
    </mj-attributes>
   
  </mj-head>
  <mj-body background-color="#E7E7E7" width="700px">
      <mj-section  background-color="#000000" padding-bottom="15px" border-radius="10px" >
      <mj-column width="100%">
      </mj-column>
    </mj-section>
    <mj-section padding-top="15px"></mj-section>
     <mj-section background-color="#000000">
      <mj-column width="100%">
      </mj-column>
    </mj-section>
    <mj-wrapper padding-top="0" padding-bottom="0" css-class="body-section">
      <mj-section background-color="#ffffff" padding-left="15px" padding-right="15px">
        <mj-column width="100%">

  <mj-text>
    <h3>Lorem ipsum dolor sit amet Lorem ipsum dolor sit amet Lorem ipsum: <strong>3</strong>. Lorem ipsum dolor sit amet Lorem ipsum dolor sit amet Lorem ipsum, lorem ipsum.
      <br></br>
      Lorem ipsum dolor sit amet Lorem ipsum dolor sit amet Lorem ipsum.</h3>
  </mj-text>
<mj-text><p>Lorem ipsum dolor sit amet Lorem ipsum dolor sit amet Lorem ipsum dolor sit amet dfsfdsfds: <strong>bleggity.blah@dsafsd.com</strong></p>
                                        <p>Lorem ipsum dolor sit amet Lorem ipsum dolor sit amet Lorem ipsum dolor sit amet dfsfdsfds <a href="https://bleggityblah/notes/6y276nghvuxn9e3ve4uc3py/">lorem ipsum</a>. Lorem ipsum dolor sit amet Lorem ipsum dolor sit amet Lorem ipsum <a href="mailto:bleggity.blah@dfsdsffd.com?subject=RE: lorem ipsum - adfdfsfds@fdsfd.com">lorem ipsum</a>.</p></mj-text>
<mj-text color="#212b35" font-weight="bold" font-size="20px" align="center">lorem ipsum</mj-text>
<mj-table> <table> <colgroup><col/><col/><col/><col/></colgroup> <tr><th>loremipsum</th><th>loremipsum</th><th>loremipsum</th><th>E-loremipsum</th></tr> <tr><td>blehy, blah</td><td>blahp</td><td>blahg</td><td>bloggy.blah@blah.com</td></tr></table> </mj-table>

        </mj-column>
      </mj-section>
      <mj-section background-color="#ffffff" padding-left="15px" padding-right="15px" padding-top="0">
      </mj-section>
      <mj-section background-color="#ffffff" padding-left="15px" padding-right="15px" padding-top="0">
        <mj-column width="100%">
          <mj-divider border-color="#DFE3E8" border-width="1px" />
        </mj-column>
      </mj-section>
      <mj-section background-color="#ffffff" padding="0 15px 0 15px">
      </mj-section>
    </mj-wrapper>
  </mj-body>
</mjml>
```

### How it should look:
![image](https://github.com/SebastianStehle/mjml-net/assets/1587819/e5d7a931-0901-4b3b-81b4-1115198d2d8f)

### How it actually looks when rendered and sent by MJML-net:
![image](https://github.com/SebastianStehle/mjml-net/assets/1587819/f74ea6e3-6dd5-4a97-8b8f-9ce243d3458f)

Thanks again for your efforts on this.

**Comment by SebastianStehle** [comment]
Thanks. I think something is fundamentally broken when parsing multiple children. Therefore the second mj-text becomes a child of the first mj-text and so on. Will have a look asap.

**Comment by SebastianStehle** [comment]
It has been fixed and released. The problem is also in your mjml:

```
<br></br>
```

is a so called void tag: https://developer.mozilla.org/en-US/docs/Glossary/Void_element.

The problem in our html reader was how we have handled them. When read a subtree, the only option was to know when the subtree has been read completely is to count the open and ending tags. We introduced the bug that a void tag was not counted when opened, but counted when closed.

e.g. in your case:

```
1: <h3>
1:   Lorem ipsum dolor sit amet Lorem ipsum dolor sit amet Lorem ipsum: 
2:    <strong>
2:   3
1:    </strong>. 
1:    Lorem ipsum dolor sit amet Lorem ipsum dolor sit amet Lorem ipsum, lorem ipsum.
1:    <br>
0:   </br> // BUG
0:    Lorem ipsum dolor sit amet Lorem ipsum dolor sit amet Lorem ipsum.
0: </h3>
```

and then the subtree was closed too early and everything went bananas after that.

Now it works like that:

```
1: <h3>
1:   Lorem ipsum dolor sit amet Lorem ipsum dolor sit amet Lorem ipsum: 
2:    <strong>
2:   3
1:    </strong>. 
1:    Lorem ipsum dolor sit amet Lorem ipsum dolor sit amet Lorem ipsum, lorem ipsum.
1:    <br> // Just skipped
1:    <br> // Just skipped
1:   </br> // Just skipped
1:    Lorem ipsum dolor sit amet Lorem ipsum dolor sit amet Lorem ipsum.
0: </h3>
```

**Comment by FixFlare** [comment]
Nice, thanks again for the quick fix - tested it, and my email template is working again.


The <br> thing is a long story - normally i'd just do <br> but as I recall when I tried to send my template using mjml-net, it threw an exception saying there was no closing tag. If you then go to MJML's live editor and type, <br> it'll automatically add the closing tag </br>


I think the correct way is probably just <br /> based on other examples I've seen directly from MJML.

Either way, it was working before even with </br>

Thanks again

**Comment by SebastianStehle** [comment]
> Either way, it was working before even with </br>

Yes, because there was some sanitation to fix invalid XML. But with 2.0 we moved from XML to HTML to get rid of that.
