### ISSUE TITLE
MJML Upgrade broke .NET href Url.Page() builder link.

### ISSUE THREAD

**Issue by webzest** [SebastianStehle/mjml-net#189]
Describe the bug:

In version 1.24, I was able to use a button to send the user the Email confirmation code with all related returned URL variables. Upgrading to a newer version, starting with 2.0 broke the URL and eliminates the ability to sent the Email Confirmation link.

**This works on version 1.24.**  Create a file with this MJML code:
```
var callbackUrl = Url.Page("/Account/ConfirmEmail", pageHandler: null, values: new { area = "Identity", userId = userNew.Id, code = code, returnUrl = returnUrl }, protocol: Request.Scheme);
string prehtml = $@"
<mj-button background-color='#D04139' border-radius='3px' font-size='18px' font-weight='normal'
    inner-padding='10px 25px' padding-bottom='30px' padding='10px 25px'><a
        href='{HtmlEncoder.Default.Encode(callbackUrl)}'
        style='color:#FFFFFF; text-decoration:none;'>Click to Verify</a>
</mj-button>
";
```
**Render it to HTML by doing:**
```
var mjmlRenderer = new MjmlRenderer();
var options = new MjmlOptions
{
    Beautify = false
};
var xml = mjmlRenderer.FixXML(prehtml, options);
var (RenderedgBody, error) = mjmlRenderer.Render(xml, options);
```
Inspect the Rendered HTML in debug mode :  (mjmlRenderer)

On version 1.24, the URL is available to the Email template and the Email button is displayed and is operational. 
In any other version greater than 1.24, the URL is not present.  In fact, there is no HTML to review at all.  For example, if I use the code for the latest version, such as 3.5, then the URL is not available in the rendered html:
```
 var (html, errors) = mjmlRenderer.Render(callbackUrl, options);
```
By inspecting html in debug mode, one can observe the missing button.

MJML environment (please complete the following information):

OS: [e.g. Windows 11]
MJML Version [e.g. 1.24 && versions 2.0 - 3.5]
MJML tool used MJML App] && copy mjml code to .NET Core app.
At this point, it does not matter what Email client is used, for the HTML is not available to generate the link or a button.

**Comment by SebastianStehle** [comment]
Have you checked the errors?

**Comment by SebastianStehle** [comment]
I have just created a super simple test and then  Ihave copied the html to a file:

My test:

```
    [Fact]
    public void Just_a_test()
    {
        var callbackUrl = "URL";

        string prehtml = $@"
<mj-button background-color='#D04139' border-radius='3px' font-size='18px' font-weight='normal'
    inner-padding='10px 25px' padding-bottom='30px' padding='10px 25px'><a
        href='{HtmlEncoder.Default.Encode(callbackUrl)}'
        style='color:#FFFFFF; text-decoration:none;'>Click to Verify</a>
</mj-button>
";

        var mjmlRenderer = new MjmlRenderer();
        var options = new MjmlOptions
        {
            Beautify = false
        };

        var (RenderedgBody, error) = mjmlRenderer.Render(prehtml, options);

    }
```
    
    My Output
    
    
![image](https://github.com/SebastianStehle/mjml-net/assets/1236435/25ee11ad-6875-4584-bfb7-dde77dbdb4fc)

    
The black border is from another window.

**Comment by SebastianStehle** [comment]
I think the problem is somewhere with the encoding. I have realized that when you have an invalid character there it stops reading. If you remove the call to the HtmlEncoder, it might just work. I can reproduce that with a sample URL that contains "\n".

**Comment by SebastianStehle** [comment]
You are right, the problem are single quotes, together with the ampersand. I have created a small example here: 
https://github.com/osjoberg/HtmlPerformanceKit/issues/6

**Comment by SebastianStehle** [comment]
Should be fixed now. I made a fork of the library and fixed the problem, wrote some tests and then released it to nuget.
