### ISSUE TITLE
mj-include does not respect order when the included file contains <mjml><mj-body>...

### ISSUE THREAD

**Issue by gareth-evans** [SebastianStehle/mjml-net#190]
According to the MJML docs

> You can wrap your external mjml files inside the default mjml > mj-body tags to make it easier to preview outside the main template.

I have this working using the official MJML extension in VS Code. However when I try the same with MJML.Net it doesn't work as expected.

Given the following example

```csharp
        var files = new Dictionary<string, string>
        {
            ["import.mjml"] = @"
                <mjml>
                    <mj-body>
                        <mj-section>
                            <mj-column>
                            <mj-text>Imported Text</mj-text>
                            </mj-column>
                        </mj-section>
                    </mj-body>
                </mjml>
"
        };

        const string source = """
                              <mjml>
                                  <mj-body>
                                      <mj-section><mj-column><mj-text color="red">Hi there!</mj-text></mj-column></mj-section>
                                      <mj-include path="import.mjml" />
                                      <mj-section><mj-column><mj-text color="red">Hello Again!</mj-text></mj-column></mj-section>
                                  </mj-body>
                              </mjml>
                              """;

        var result = TestHelper.Render(source, new MjmlOptions
        {
            FileLoader = () => new InMemoryFileLoader(files)
        });
```

The "Imported Text" element is rendered before the other two elements instead of between them.

I've done some digging and can see that each BodyComponent creates it's own buffer and then adds it to GlobalContext. What's happening here is
1. The first body creates a buffer (Buffer1) and "Hi there" is written to it. 
2. The nested body creates a new buffer (Buffer2), 
3. "Imported Text" is written to Buffer2.
4.  Buffer2 is added to GlobalData
5. "Hello Again!" is written to Buffer1 
6. Buffer1 is added to GlobalData
7. Buffer2 and then Buffer1 are written out in the final render.

I did think of trying to fix it but wasn't sure of the best approach. My initial thought was to yield and discard Root and Body components if they exist in an Include component.

**Comment by SebastianStehle** [comment]
Sounds like a good idea to implement it without buffering. PR is welcome
