### ISSUE TITLE
Table not rendered in modern Outlook Client 3.1.0 > 3.11.0

### ISSUE THREAD

**Issue by FixFlare** [SebastianStehle/mjml-net#194]
There seems to be two versions of Outlook in use by Microsoft at the moment. One dependent on the WebView2 which I think is shared with their Android app.

When using this modern version my e-mail template that was working before now no longer renders the table data.

Here is an example that demonstrates the problem.

```mjml
<mjml>
  <mj-head>
    <mj-title>test</mj-title>
    <mj-preview>test</mj-preview>
    <mj-attributes>
      <mj-all font-family="Calibri, Arial"></mj-all>
      <mj-table></mj-table>
      <mj-text font-weight="400" font-size="16px" color="#000000" line-height="24px"></mj-text>
    </mj-attributes>
   
  </mj-head>
  <mj-body background-color="#E7E7E7" width="700px">
      <mj-section  background-color="#000000" padding-bottom="15px" border-radius="10px" >
      <mj-column width="100%">
      </mj-column>
    </mj-section>
    <mj-section padding-top="15px"></mj-section>
     <mj-section background-color="#000000">
      <mj-column width="100%">
      </mj-column>
    </mj-section>
    <mj-wrapper padding-top="0" padding-bottom="0" css-class="body-section">
      <mj-section background-color="#ffffff" padding-left="15px" padding-right="15px">
        <mj-column width="100%">

  <mj-text>
    <h3>Lorem ipsum dolor sit amet Lorem ipsum dolor sit amet Lorem ipsum: <strong>3</strong>. Lorem ipsum dolor sit amet Lorem ipsum dolor sit amet Lorem ipsum, lorem ipsum.
      Lorem ipsum dolor sit amet Lorem ipsum dolor sit amet Lorem ipsum.</h3>
  </mj-text>
<mj-text><p>Lorem ipsum dolor sit amet Lorem ipsum dolor sit amet Lorem ipsum dolor sit amet dfsfdsfds: <strong>bleggity.blah@dsafsd.com</strong></p>
                                        <p>Lorem ipsum dolor sit amet Lorem ipsum dolor sit amet Lorem ipsum dolor sit amet dfsfdsfds <a href="https://bleggityblah/notes/6y276nghvuxn9e3ve4uc3py/">lorem ipsum</a>. Lorem ipsum dolor sit amet Lorem ipsum dolor sit amet Lorem ipsum <a href="mailto:bleggity.blah@dfsdsffd.com?subject=RE: lorem ipsum - adfdfsfds@fdsfd.com">lorem ipsum</a>.</p></mj-text>
<mj-text color="#212b35" font-weight="bold" font-size="20px" align="center">lorem ipsum</mj-text>
<mj-table> <table> <colgroup><col/><col/><col/><col/></colgroup> <tr><th>loremipsum</th><th>loremipsum</th><th>loremipsum</th><th>E-loremipsum</th></tr> <tr><td>blehy, blah</td><td>blahp</td><td>blahg</td><td>bloggy.blah@blah.com</td></tr></table> </mj-table>

        </mj-column>
      </mj-section>
      <mj-section background-color="#ffffff" padding-left="15px" padding-right="15px" padding-top="0">
      </mj-section>
      <mj-section background-color="#ffffff" padding-left="15px" padding-right="15px" padding-top="0">
        <mj-column width="100%">
          <mj-divider border-color="#DFE3E8" border-width="1px" />
        </mj-column>
      </mj-section>
      <mj-section background-color="#ffffff" padding="0 15px 0 15px">
      </mj-section>
    </mj-wrapper>
  </mj-body>
</mjml>
```

When looking at the rendered html it looks like the table gets created with a 0 dimension.

It seems to work fine with the mjml "try it live" feature: [https://mjml.io/try-it-live/LKFi1sfr2V](https://mjml.io/try-it-live/LKFi1sfr2V)

Interestingly enough, it does not happen with the older Outlook Desktop version (the one without webview)

Outlook Version Desktop:
Microsoft Outlook Version 1.2024.529.200 (Production).
Client Version is 20240524003.09 .
WebView2 Version is 125.0.2535.79

Android Outlook Version:
4.2422.0 

Looks correct in old Desktop Outlook:
![image](https://github.com/SebastianStehle/mjml-net/assets/1587819/5bb3403d-3573-4fa7-91bf-13afa14f3aef)

Table data is missing in Android or Newer Outlook Version based on WebView
![image](https://github.com/SebastianStehle/mjml-net/assets/1587819/1aa24060-0cae-49f9-813e-322cc07bb409)

**Comment by SebastianStehle** [comment]
I have added your example to our tests. We run the code through mjml (using Node) and then our own implementation and compare the results on a semantic level (so we ignore stuff like attribute orders and whitespaces and so on). And the test is green. So I would say, that the problem is more on the mjml level and not on our port.

**Comment by FixFlare** [comment]
Yeah, I think you're right.

Problem persists when I take generated HTML from MJML try-it-live and send with powershell's send-mailmessage.

I've logged the issue upstream on MJML's github.

[#2869](https://github.com/mjmlio/mjml/issues/2869)


Thanks for the quick response

**Comment by SebastianStehle** [comment]
I have subscribed to the issue, so that we can also implement the fix if they decide to solve the problem. Feel free to ping me, just in case I forget it.

**Comment by SebastianStehle** [comment]
I guess I can close that.

**Comment by FixFlare** [comment]
Yes, thanks for the help @SebastianStehle
