### ISSUE TITLE
Default language attribute lang="und" is an invalid value

### ISSUE THREAD

**Issue by Namoshek** [SebastianStehle/mjml-net#195]
We use the library to generate customer emails of which some are attached to tickets of internal tools. After an update of the library, some of the tools (e.g. SAP) are unable to open the emails due to an invalid `lang="und"` attribute on the `<html>` tag. The change seems to have been introduced in #191.

The issue can easily be fixed by adding a custom language on the root element (which is a good idea anyway):
```xml
<mjml lang="de">
  ...
</mjml>
```

However, [according to the Mozilla documentation on the `lang` attribute](https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes/lang) and [WHATWG](https://html.spec.whatwg.org/#the-lang-and-xml:lang-attributes), the default value is an empty string and there is no mention of `und` anywhere in this documentation. So I'm wondering where this value is coming from and if its actually the right default?

---

I've also looked into [RFC 5646](https://datatracker.ietf.org/doc/html/rfc5646) regarding the `lang` attribute and even though it actually defines `und` as a value, it also has an interesting note regarding the use of `lang="und"`:

> The 'und' (Undetermined) primary language subtag identifies linguistic content whose language is not determined. This subtag SHOULD NOT be used unless a language tag is required and language information is not available or cannot be determined.  Omitting the language tag (where permitted) is preferred.  The 'und' subtag might be useful for protocols that require a language tag to be provided or where a primary language subtag is required (such as in "und-Latn").  The 'und' subtag MAY also be useful when matching language tags in certain situations.

**Comment by SebastianStehle** [comment]
Hi,

We just copy the mjml behavior. See:
https://github.com/mjmlio/mjml/blob/824cd66aa8b635bf35c1121068a07c655b226b8b/doc/components_1.md?plain=1#L36

So I think the behavior is as intended

**Comment by Namoshek** [comment]
Ah, I see. In that case consider this issue as documentation for whoever is affected by a similar issue in the future.

Thanks for the nice port to .NET by the way! 🍺
