### ISSUE TITLE
inner-border is not working as expected

### ISSUE THREAD

**Issue by schreys** [SebastianStehle/mjml-net#204]
Given this example:

```
<mjml>
  <mj-head>
    <mj-title>Hello World Example</mj-title>
  </mj-head>
  <mj-body>
    <mj-section>
      <mj-column padding="0" inner-border="1px solid black">
        <mj-text >
          Hello World!
        </mj-text>
      </mj-column>
    </mj-section>
  </mj-body>
</mjml>
```

returns following table format, which is invalid html:

```
<table
        border="0"
        cellpadding="0"
        cellspacing="0"
        role="presentation"
        width="100%"
        style="
          border: 1px solid black;
          border-bottom: black;
          border-left: solid;
          border-right: solid;
          border-top: 1px;
        "
      >
```

When investigating the code I found that the problem occurs in the TemplateField class of the Generator:

![inner-border](https://github.com/user-attachments/assets/1ee6bfa2-f99c-43e6-a8d0-138aec78cf38)

**Comment by SebastianStehle** [comment]
Thank you for investigating. Do you want to provide a PR?

**Comment by schreys** [comment]
thanks!

**Comment by schreys** [comment]
Can you have a look at the build, as a file is missing now. Thanks!

**Comment by schreys** [comment]
Sorry, but can you have a look at the build, a test seems to fail
