### ISSUE TITLE
Mj-include not working help please.

### ISSUE THREAD

**Issue by fredyfx** [SebastianStehle/mjml-net#205]
There is a master template where I have 2 files: `header.mjml` and `footer.mjml`.

On a 3rd file, I have `welcome.mjml` where I pass a dynamic location:

`<mj-include path="@Model.HeaderLocation" />`
`<mj-include path="@Model.FooterLocation" />`

In these 2 locations, the Path is a full path from C:\ until the mjml file.

The problem: both locations are not getting rendered, they are ignored.

I tried the following code:
```

  Func<IFileLoader> customFileLoader = () =>
  {
      return new InMemoryFileLoader(new Dictionary<string, string>
      {
          { "GeneralHeader.mjml", File.ReadAllText(Path.Combine(templatesFolder, "GeneralHeader.mjml")) },
          { "GeneralFooter.mjml", File.ReadAllText(Path.Combine(templatesFolder, "GeneralFooter.mjml")) }
      });
  };

  // Convert Razor result to HTML using MJML
  var mjmlRenderer = new MjmlRenderer();
  var options = new MjmlOptions
  {
      Beautify = true,
      FileLoader = customFileLoader
  };

  var (html, errors) = mjmlRenderer.Render(razorResult, options);
  if (errors is not null && errors.Any())
  {
      _logger.LogError($"Error on generating file: {errors}");
  }

  return html;
```

Temporary solution: Copy and paste on each "content" file, the header and the footer (it works but It is not optimal).

How can I use the FileLoader in MjmlOptions and pass the path where all my mjml templates are located?

**Comment by SebastianStehle** [comment]
How should the model syntax be handled? I don't get it. It is not razor

**Comment by fredyfx** [comment]
I use RazorLight (Version 2.3.1) to render my data properly, everything is fine except the part of `mj-include`

The data rendered in `@Model.HeaderLocation`

 is: 

`C:\Dev\project\Backend\Src\project.Infrastructure\bin\Debug\net8.0\EmailTemplates\GeneralHeader.mjml`

Same situation for the FooderLocation.

The worflow I have is:

Razor -> render (razorResult) -> this has everything on MJML -> Render this using MJML and magic! the HTML is ready to go.

The problem is the `mjml-include`. For some reason it doesn't include the file where it should be. Any idea?

**Comment by SebastianStehle** [comment]
No, sorry..you could implement your own file loader and see if it is called. I guess you also want to run razor here.

**Comment by fredyfx** [comment]
I guess I'm not clear enough. I am able to run Razor without problem and I have your amazing library up and running along Razor. The problem is the render of MJML with `mjml-include` that for some reason is not pulling the code of a MJML file where it should. I have the right path of a mjml file without any razor in it. It's just a header and a footer. and I'm running out of ideas. Thanks.

**Comment by LiamRiddell** [comment]
> I guess I'm not clear enough. I am able to run Razor without problem and I have your amazing library up and running along Razor. The problem is the render of MJML with `mjml-include` that for some reason is not pulling the code of a MJML file where it should. I have the right path of a mjml file without any razor in it. It's just a header and a footer. and I'm running out of ideas. Thanks.

Hi @fredyfx, I understand your use case. You need to use a custom file loader, this can be done by creating a class that implements [IFileLoader](https://github.com/SebastianStehle/mjml-net/blob/351963cb31f13c6a8c244af82ae8758efc9ad74d/Mjml.Net/IFileLoader.cs#L6-L17).

Inside of the `LoadMethod` function you may be able to just do a simple implementation such as the following:
```csharp
public class LocalFileLoader : IFileLoader
{
    public string? LoadText(string path) {
        return File.ReadAllText(path);
    }
}
```

**Comment by SebastianStehle** [comment]
My point of the custom loader is to see whether it is loaded at all. If you have a small repo to reproduce it, I can also have a look. Ideally as a PR to this repo and as a custom unit test, because this is easiest to debug.

**Comment by SebastianStehle** [comment]
Closed due to inactivity
