### ISSUE TITLE
When moving from version 3.8 to 3.9 I now need to call HttpUtility.HtmlDecode on the rendered html

### ISSUE THREAD

**Issue by drgrieve** [SebastianStehle/mjml-net#206]
I have logic functions that build up html for example adding strong tags or <br> to add pseudo list items.

Wondering on why this changed, and on the expectation on how I should be building text strings that will get wrapped by mj-text elements.

Thanks

```
Was:
<strong>Mon 21st October 2024</strong>
Now:
&lt;strong&gt;Mon 21st October 2024&lt;/strong&gt;
```

**Comment by SebastianStehle** [comment]
Can you reproduce it with the latest version? Because we have tests for that, which are all green: 

https://github.com/SebastianStehle/mjml-net/blob/main/Tests/Components/Outputs/TextWithHtml.html

**Comment by drgrieve** [comment]
Yes I get the same issue. I'll add in more details like source to output just out of time for today.

**Comment by SebastianStehle** [comment]
If you can just provide a test, it would be good :)

**Comment by drgrieve** [comment]
So for others that stumble across this: 

I was previously building test strings in razor and not using Html.Raw or HtmlString, so razor was of course encoding the html.

3.8 and prior of mjml.net used to decode the html for us, so this behaviour of razor slipped my mind since mjml handled it for me.

So I can continue to be forgetful before passing the html string to mjml to render I call HttpUtility.HtmlDecode on it and thus keep the old lazy behaviour (as I trust my inputs)

Thanks for the great library.
