### ISSUE TITLE
V2 Status

### ISSUE THREAD

**Issue by SebastianStehle** [SebastianStehle/mjml-net#72]
I had a look to the template gallery and counted the tag usage:

```
mj-column           : 279 done
mj-text             : 204 done
mj-section          : 183 done
mj-image            : 154 done
mj-button           : 50 done
mj-raw              : 25 done
mj-body             : 22 done
mj-social           : 19 done
mj-spacer           : 17 done
mj-divider          : 15 done
mj-class            : 12 done
mj-head             : 10 done
mj-navbar           : 10 done
mj-attributes       : 8 done
mj-carousel         : 7
mj-title            : 6 done
mj-all              : 6 done
mj-style            : 6 done
mj-font             : 5 done
mj-group            : 4 done
mj-wrapper          : 3 done
mj-table            : 1 done
```

## Tasks

* [x] #75
* [x] #76
* [x] #77
* [x] #78

## QA

* [x] Compile all templates
* [x] Compile all templates dynamically with mjml so we can track errors.

## Others

* [x] #73

**Comment by SebastianStehle** [comment]
@LiamRiddell I pushed a commit where I have written a test which runs the mjml CLI over all templates and compares that.

It helped me to fix a few issues, but not everything is green yet.

The pending issues are these things:

1. Rounding errors and different behaviors (we can ignore that)
2. Bugs in mj-section (please have a look)
3. Bugs that need the text fix (please have a look)

Would be great if you can have a closer look to get more of them green.

You have to remove the `Skip = "..."` and install the mjml-cli for that.

**Comment by SebastianStehle** [comment]
ALL templates compile, except one that uses carousel :)

**Comment by SebastianStehle** [comment]
I had to make mini fixes in some templates because they are broken, but so far so good :)

**Comment by LiamRiddell** [comment]
I'm going to start the Carousel now.

**Comment by SebastianStehle** [comment]
In the complex templates test, there is one template disabled. Can you test this one as well? You have to install mjml with `npm i mjml -g` for that.
