### ISSUE TITLE
Rename Projects

### ISSUE THREAD

**Issue by LiamRiddell** [SebastianStehle/mjml-net#93]
Currently, I feel the project names are disconnected. Here's what I think we should call them:

- Mjml.Net
- Mjml.Net.Benchmark
- Mjml.Net.Generator
- Mjml.Net.Tests
- Tools

@SebastianStehle, I'd like you thoughts on this as you maintain lots of OS projects :)

**Comment by SebastianStehle** [comment]
It is personal preference. I tend to give tests and tools shorter names, but I am not against it.

**Comment by LiamRiddell** [comment]
> It is personal preference. I tend to give tests and tools shorter names, but I am not against it.

That's very true. I've always tried to contain them under wider solution names. I'm happy to do the changes if you're happy?

**Comment by SebastianStehle** [comment]
Can we just keep tools?
