### ISSUE TITLE
Update README and NuGet

### ISSUE THREAD

**Issue by LiamRiddell** [SebastianStehle/mjml-net#95]
- [x] Remove Experimental
- [x] Add new benchmark results to Readme.
- [x] Update the project description to better reflect the current state.
- [x] Mention the cleanup method => slower
- [x] Mention some options (beautify) and the performance impact => slower
- [x] Mesure performance with memory allocations
- [x] Fix the benchmark templates
- [x] Update NuGet information
- [x] Deprecate LiamRiddell/MjmlDotNet and Archive
- [ ] Add MIT License @SebastianStehle 
- [ ] Project Description @SebastianStehle

**Comment by LiamRiddell** [comment]
I'm just putting it here so I remember everything :D

**Comment by SebastianStehle** [comment]
I am so glad that we are in such a good state now. I have not expected that all templates would become green :)

**Comment by LiamRiddell** [comment]
> I am so glad that we are in such a good state now. I have not expected that all templates would become green :)

Yeah, It's really solid and nice to see actual tests for this kind of project. Also, I updated the NuGet package version to 1.0.0 but it's not updated. Am I missing something?

**Comment by SebastianStehle** [comment]
Please also remove the N/A

**Comment by SebastianStehle** [comment]
> Also, I updated the NuGet package version to 1.0.0 but it's not updated. Am I missing something?

No, it worked as expected. It just takes a while, but I see it in nuget.

**Comment by SebastianStehle** [comment]
Would be interesting to have memory allocations in the benchmark.

**Comment by LiamRiddell** [comment]
Most of  the stuff is done. We probably should stop both:

`Mjml.Net.Generator` and `Mjml.Net.Benchmark` being published to NuGet :)

**Comment by SebastianStehle** [comment]
The generator is by purpose because you need it for custom extensions.
